use anyhow::{Context, Result};
use reqwest::Client;
use serde_json::{json, Value};

use crate::config::Susfile;

pub fn tools_for_agent(agent: &str, cfg: &Susfile, cve_tools_enabled: bool) -> Vec<Value> {
    match agent {
        "dispatch_agent" => vec![
            tool_no_args("read_plan", "Read plan.md"),
            tool_new_analyst(),
            tool_no_args("new_strategist", "Spawn strategist agent"),
            tool_no_args("new_reporter", "Spawn reporter agent"),
        ],
        "strategist_agent" => {
            let mut tools = vec![
                tool_no_args("read_plan", "Read plan.md"),
                tool_single_id("read_note", "Read notes/<task-id>.md"),
                tool_no_args("read_attack_model", "Read attack_model.md"),
                tool_no_args(
                    "read_tool_data",
                    "Read all tool_data outputs generated by analyst tool calls",
                ),
                tool_update_attack_model(),
                tool_update_plan(),
            ];
            if cve_tools_enabled {
                tools.extend(cve_tools());
            }
            tools
        }
        "analyst_agent" => {
            let mut tools = vec![
                tool_single_id("claim_task", "Claim task and set to pending"),
                tool_single_id("complete_task", "Mark task complete"),
                json!({"type":"function","function":{"name":"add_note","description":"Append note text to notes/<task-id>.md","parameters":{"type":"object","properties":{"id":{"type":"string"},"note":{"type":"string"}},"required":["id","note"]}}}),
            ];

            if cve_tools_enabled {
                tools.extend(cve_tools());
            }

            for cli_tool in &cfg.tools.cli {
                let mut properties = serde_json::Map::new();
                let mut required = Vec::new();
                for arg in &cli_tool.args {
                    properties.insert(
                        arg.name.clone(),
                        json!({"type": "string", "description": arg.description}),
                    );
                    required.push(arg.name.clone());
                }

                tools.push(json!({
                    "type": "function",
                    "function": {
                        "name": cli_tool.name,
                        "description": cli_tool.description,
                        "parameters": {
                            "type": "object",
                            "properties": properties,
                            "required": required
                        }
                    }
                }));
            }

            tools
        }
        "report_agent" => vec![
            tool_no_args("read_plan", "Read plan.md"),
            tool_no_args("read_attack_model", "Read attack_model.md"),
            tool_no_args(
                "read_tool_data",
                "Read all tool_data outputs generated by analyst tool calls",
            ),
            tool_write_report(),
        ],
        _ => vec![],
    }
}

fn cve_tools() -> [Value; 2] {
    [
        json!({"type":"function","function":{"name":"cve_search","description":"Search CVE database by query text and return raw records","parameters":{"type":"object","properties":{"query":{"type":"string"}},"required":["query"]}}}),
        json!({"type":"function","function":{"name":"cve_show","description":"Get one CVE and affected products by CVE ID","parameters":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}}}),
    ]
}

fn tool_no_args(name: &str, description: &str) -> Value {
    json!({"type":"function","function":{"name":name,"description":description,"parameters":{"type":"object","properties":{}}}})
}

fn tool_single_id(name: &str, description: &str) -> Value {
    json!({"type":"function","function":{"name":name,"description":description,"parameters":{"type":"object","properties":{"id":{"type":"string"}},"required":["id"]}}})
}

fn tool_new_analyst() -> Value {
    json!({"type":"function","function":{"name":"new_analyst","description":"Spawn analyst agent for a task id","parameters":{"type":"object","properties":{"task_id":{"type":"string"}},"required":["task_id"]}}})
}

fn tool_update_plan() -> Value {
    json!({"type":"function","function":{"name":"update_plan","description":"Write full markdown to plan.md","parameters":{"type":"object","properties":{"updated_markdown":{"type":"string"}},"required":["updated_markdown"]}}})
}

fn tool_update_attack_model() -> Value {
    json!({"type":"function","function":{"name":"update_attack_model","description":"Write full markdown to attack_model.md","parameters":{"type":"object","properties":{"updated_model":{"type":"string"}},"required":["updated_model"]}}})
}

fn tool_write_report() -> Value {
    json!({"type":"function","function":{"name":"write_report","description":"Write full markdown to report.md","parameters":{"type":"object","properties":{"markdown":{"type":"string"}},"required":["markdown"]}}})
}

pub async fn create_chat_completion(
    client: &Client,
    api_key: &str,
    model: &str,
    messages: &[Value],
    tools: &[Value],
) -> Result<Value> {
    let body = json!({
        "model": model,
        "messages": messages,
        "tools": tools,
        "tool_choice": "auto"
    });

    let res = client
        .post("https://api.openai.com/v1/chat/completions")
        .bearer_auth(api_key)
        .json(&body)
        .send()
        .await
        .context("chat completion request failed")?;

    if !res.status().is_success() {
        let status = res.status();
        let text = res.text().await.unwrap_or_default();
        return Err(anyhow::anyhow!("OpenAI API {}: {}", status, text));
    }

    let v: Value = res
        .json()
        .await
        .context("failed to parse chat completion response")?;
    Ok(v)
}
